### ISSUE TITLE
Include ABAP Projects from dotabap.org in the artifacts

### ISSUE THREAD

**Issue by gregorwolf** [SAP-samples/artifact-of-the-month#1]
Hi @IObert,

thank you for this initiative. It would be great if the list powering https://dotabap.org/ that is maintained in the [dotabap-list](https://github.com/dotabap/dotabap-list) project can be included in the artifacts. The list is provided as a JSON format and can be accessed at: https://raw.githubusercontent.com/dotabap/dotabap-list/main/list.json.

Hope that someone has the time to contribute this. I can just provide the idea in the moment.

CU
Gregor

**Comment by larshp** [comment]
and https://list.dotabap.org/list.json and more information via https://generated.dotabap.org/generated.json

but I'm not sure what information is needed? something like the traffic stats is not public accessible

**Comment by gregorwolf** [comment]
As far as I see, the list of repos must be added to [analyzer/src/providers/gh-repo.ts#L7](https://github.com/SAP-samples/artifact-of-the-month/blob/main/analyzer/src/providers/gh-repo.ts#L7)

**Comment by larshp** [comment]
ahh, okay, it looks at stars and forks

**Comment by IObert** [comment]
We could create a new "ABAP type" as well but then I'd make sense to have some DL count or so.

But I think it's, for now, enough to add them to the list of GitHub repos.

I can take this item :)

**Comment by IObert** [comment]
Done, all items of that list should be added automatically in the next run (on Sept 1st)
